site_name: Mollusc
site_dir: .site
docs_dir: src/doc

pages:
  - About: index.md
  - New project: new-project.md
  - Bootstrap: bootstrap.md
  - Shell scripting: shell.md
  - Changelog: changelog.md
  - Develop: dev.md
  - TODO: todo.md
